name: Runner

on:
  workflow_dispatch:
    inputs:
      OS:
        description: "Operating System"
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-22.04
        required: true
      config:
          description: "Config BASE64"
          required: true

jobs:
  run-script:
    runs-on: ${{ github.event.inputs.OS }}
    name: "Runner Script (${{ github.event.inputs.OS }})"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: Install cloudflared
        timeout-minutes: 3
        run: |
          sudo wget -O /root/cloudflared.deb "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
          sudo apt install /root/cloudflared.deb
          cloudflared --version || exit 1
      - name: Build DGB Reader
        run: |
          sudo g++ -o /usr/bin/dgb-reader "$GITHUB_WORKSPACE/storage/dgb-reader.cpp"
      - name: Init
        id: init
        shell: bash
        continue-on-error: true
        run: |
          sudo mkdir -m 770 -p /input /env /local /output
          sudo mkdir -m 771 -p /ws
          sudo chown runner:docker /input /env /local /output
          wget -O /input/config.dgb ${{ github.event.inputs.config }} || true
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup cloudflared
        run: |
          echo "Get Files"
          cloudflared_cert=$(dgb-reader cloudflared cert)
          cloudflared_config=$(dgb-reader cloudflared config)
          cloudflared_tunnel=$(dgb-reader cloudflared tunnel)
          
          sudo mkdir -m 700 -p /root/.cloudflared
          rclone copyto "$cloudflared_cert" cert.pem || { echo "Failed to copy cert.pem"; exit 1; }
          rclone copyto "$cloudflared_config" config.yml || { echo "Failed to copy config.yml"; exit 1; }
          rclone copyto "$cloudflared_tunnel" tunnel.json || { echo "Failed to copy tunnel.json"; exit 1; }
          
          sudo mv cert.pem /root/.cloudflared/cert.pem
          sudo mv config.yml /root/.cloudflared/config.yml
          sudo mv tunnel.json "/root/.cloudflared/${{ secrets.TUNNEL_ID }}.json"
          
          sudo rm -f cert.pem config.yml tunnel.json

          [ ! -f "cert.pem" ] && [ ! -f "config.yml" ] && [ ! -f "tunnel.json" ] || { echo "Temporary files were not removed"; exit 1; }

          echo "Rename hostname"
          sudo sed -i "s|test12341234\.freesites\.eu\.org|ws-dgbaodev-$(dgb-reader main id).freesites.eu.org|g" /root/.cloudflared/config.yml || { echo "Failed to rename hostname"; exit 1; }
          sudo cloudflared tunnel route dns websocket-dgbaodev "ws-dgbaodev-$(dgb-reader main id).freesites.eu.org" >/dev/null 2>&1 || true
          echo "Run"
          sudo cloudflared tunnel run websocket-dgbaodev > /output/cloudflared.log 2>&1 &
          pid_x=$!
          echo $pid_x | sudo tee /root/cloudflared.pid > /dev/null

          sudo chmod 700 -R /root/.cloudflared
          sudo chmod 600 /root/cloudflared.pid
      - name: Create user - runner_clone
        run: |
          sudo useradd -m -d /runner runner_clone
          echo 'runner_clone:Runner_clone_0@' | sudo chpasswd
          sudo chmod -R 775 /runner
          sudo chown runner_clone:docker /runner
      - name: Init Programs
        timeout-minutes: 10
        run: |
          cd /runner
          for i in $(dgb-reader init apt repository); do
            sudo add-apt-repository --yes $i
          done
          for i in $(dgb-reader init apt packages); do
            sudo apt install $i -y
          done
          rclone copyto "$(dgb-reader runner script init)" /runner/init.sh || { echo "Failed to copy init.sh"; exit 1; }
          sudo chown runner_clone:docker /runner/init.sh
          sudo chmod 775 /runner/init.sh
          rclone copyto "$(dgb-reader runner script script)" /runner/script || { echo "Failed to copy script"; exit 1; }
          sudo chown runner_clone:docker /runner/script
          sudo chmod 775 /runner/script
          sudo -u runner_clone bash /runner/init.sh > /output/init_log.log 2>&1
          touch /output/script.output.log /output/ws.log /output/init_ws.log
          sudo chmod 640 /output/script.output.log /output/ws.log /output/init_ws.log
      - name: Init WS
        run: |
          cd /ws
          sudo npm init -y
          sudo npm install ws jsonwebtoken dotenv uuid winston node-pty
          ID="$(dgb-reader main id)"
          Auth_Callback_Config="$(dgb-reader return callback auth)"
          COMMAND="$(dgb-reader runner script command)"
          CallBack="$(dgb-reader return callback program)"
          rclone copyto "$CallBack" /input/callback.js
          rclone copyto "$Auth_Callback_Config" /output/auth_config.dgb
          echo "WS=wss://ws-dgbaodev-$(dgb-reader main id).freesites.eu.org" | sudo tee -a /output/auth_config.dgb > /dev/null
          sudo mv /output/auth_config.dgb ./config.dgb
          sudo mv /input/callback.js ./callback.js
          rclone copyto "$(sudo dgb-reader auth program)" /input/generate_token.js
          sudo mv /input/generate_token.js ./generate_token.js
          sudo chown root:root ./config.dgb ./generate_token.js ./callback.js
          sudo chmod 700 ./config.dgb ./generate_token.js ./callback.js
          sudo touch .env
          echo "JWT_SECRET=$(sudo dgb-reader auth secret)" | sudo tee -a .env > /dev/null
          echo "USERID=$(sudo dgb-reader auth uid)" | sudo tee -a .env > /dev/null
          echo "USERNAME=$(sudo dgb-reader auth username)" | sudo tee -a .env > /dev/null
          echo "ROLE=$(sudo dgb-reader auth role)" | sudo tee -a .env > /dev/null
          echo "ID=$ID" | sudo tee -a .env > /dev/null
          echo "PORT=9999" | sudo tee -a .env > /dev/null
          echo "COMMAND=\"$COMMAND\"" | sudo tee -a .env > /dev/null
          sudo node ./generate_token.js
          sudo cp ./config.dgb /output/auth_config.dgb
          sudo chown runner:docker /output/auth_config.dgb
          sudo chmod 775 /output/auth_config.dgb
          rclone copyto /output/auth_config.dgb "$Auth_Callback_Config"
          sudo rm -f /output/auth_config.dgb
          
      - name: Run Programs With WS
        run: |
          if ! sudo ps -p $(sudo cat /root/cloudflared.pid) > /dev/null 2>&1; then
            echo "Cloudflared tunnel failed to start"
            exit 1
          fi
          cd /ws
          sudo node ./callback.js


      - name: Kill cloudflared
        if: always()
        run: |
          if sudo [ -f /root/cloudflared.pid ]; then
            sudo kill $(sudo cat /root/cloudflared.pid) && echo "Cloudflared stopped successfully" || echo "Failed to stop cloudflared"
            sudo rm -f /root/cloudflared.pid
            sudo rm -rf /root/.cloudflared
          else
            echo "No PID file found."
          fi
      - name: Post Log
        if: always()
        run: |
          sudo chown runner:docker /output/cloudflared.log
          sudo chmod 770 /output/cloudflared.log
          sudo chown runner:docker /output/init_log.log
          sudo chmod 770 /output/init_log.log
          rclone copyto /output/cloudflared.log "$(dgb-reader debug log)/$(dgb-reader main id)_cloudflared.log"
          rclone copyto /output/init_log.log "$(dgb-reader runner script init_log)"
          rclone copyto /output/script.output.log "$(dgb-reader runner script log)/output.log"
          rclone copyto /output/ws.log "$(dgb-reader runner script log)/ws.log"
          rclone copyto /output/init_ws.log "$(dgb-reader runner script log)/init_ws.log"


