name: Runner

on:
  workflow_dispatch:
    inputs:
      OS:
        description: "Operating System"
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-22.04
        required: true
      config:
          description: "Config URL"
          required: true
      ID:
        description: "ID JOB"
        default: "RANDOM"
        required: false

jobs:
  run-script:
    runs-on: ${{ github.event.inputs.OS }}
    name: "Runner Script (${{ github.event.inputs.OS }}; ${{ github.event.inputs.ID }})"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: Set ID
        id: set_id
        run: |
          if [ "${{ github.event.inputs.ID }}" == "RANDOM" ]; then
            RANDOM_ID=$(uuidgen)
            echo "ID << RANDOM_ID: $RANDOM_ID"
            echo "JID=$RANDOM_ID" >> $GITHUB_OUTPUT
          else
            echo "ID << INPUT_ID: ${{ github.event.inputs.ID }}"
            echo "JID=${{ github.event.inputs.ID }}" >> $GITHUB_OUTPUT
          fi
      - name: Build DGB Reader
        run: |
          sudo g++ -o /usr/bin/dgb-reader "$GITHUB_WORKSPACE/storage/dgb-reader.cpp"
      - name: Init
        id: init
        shell: bash
        continue-on-error: true
        run: |
          sudo mkdir -m 775 -p /runner /input /env /local /output
          sudo chown runner:docker /runner /input /env /local /output
          wget -O /input/config.dgb ${{ github.event.inputs.config }} || true

      - name: Run tests
        run: |
          echo "Test DGB Reader"
          echo "--------------------------------------------"
          echo "Main/ID"
          echo
          dgb-reader main id
          echo
          echo "--------------------------------------------"
          echo "Init/APT/Repository"
          echo
          dgb-reader init apt repository
          echo
          echo "KEY 0"
          echo
          dgb-reader init apt repository 0
          echo
          echo "KEY 1"
          echo
          dgb-reader init apt repository 1
          echo
          echo "--------------------------------------------"
          echo "Init/APT/Packages"
          echo
          dgb-reader init apt packages
          echo
          echo "--------------------------------------------"
          echo "Init/RClone/Host"
          echo
          dgb-reader init rclone host
          echo
          echo "--------------------------------------------"
          echo "Init/RClone/Main"
          echo
          dgb-reader init rclone main
          echo
          echo "--------------------------------------------"
          echo "Init/RClone/Packages"
          echo
          dgb-reader init rclone packages
          echo
          echo "--------------------------------------------"
          echo "Init/RClone/Backup"
          echo
          dgb-reader init rclone backup
          echo
          echo "--------------------------------------------"
          echo "Return/Callback/HTTPS"
          echo
          dgb-reader return callback https
          echo
          echo "--------------------------------------------"
          echo "Return/Callback/WS"
          echo
          dgb-reader return callback ws
          echo
          echo "--------------------------------------------"
          echo "Return/Callback/Auth"
          echo
          dgb-reader return callback auth
          echo
          echo "--------------------------------------------"
          echo "Runner/Script/Init"
          echo
          dgb-reader runner script init
          echo
          echo "--------------------------------------------"
          echo "Runner/Script/Script"
          echo
          dgb-reader runner script script
          echo
          echo "--------------------------------------------"
          echo "Runner/Script/Args"
          echo
          dgb-reader runner script args
          echo
          echo "--------------------------------------------"
          echo "Runner/Script/Program"
          echo
          dgb-reader runner script program
          echo
