name: Runner

on:
  workflow_dispatch:
    inputs:
      OS:
        description: "Operating System"
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-22.04
        required: true
      config:
          description: "Config URL"
          required: true
      ID:
        description: "ID JOB"
        default: "RANDOM"
        required: false

jobs:
  run-script:
    runs-on: ${{ github.event.inputs.OS }}
    name: "Runner Script (${{ github.event.inputs.OS }}; ${{ github.event.inputs.ID }})"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set ID
        id: set_id
        run: |
          if [ "${{ github.event.inputs.ID }}" == "RANDOM" ]; then
            RANDOM_ID=$(uuidgen)
            echo "ID << RANDOM_ID: $RANDOM_ID"
            echo "JID=$RANDOM_ID" >> $GITHUB_OUTPUT
          else
            echo "ID << INPUT_ID: ${{ github.event.inputs.ID }}"
            echo "JID=${{ github.event.inputs.ID }}" >> $GITHUB_OUTPUT
          fi
      - name: Setup Rclone
          uses: AnimMouse/setup-rclone@v1
          with:
            rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: Init
        id: init
        shell: bash
        continue-on-error: true
        run: |
          sudo mkdir -m 775 -p /runner /input /env /local /output
          sudo chown runner:docker /runner /input /env /local /output
          wget -O /input/config.dgb ${{ github.event.inputs.config }} || true

      - name: Run tests
        run: |
          echo "-----------------------------------------------"
          echo "Host:"
          rclone ls host:
          echo "-----------------------------------------------"
          echo "Drive nhatgg81:"
          rclone ls drive-nhatgg81:
          echo "-----------------------------------------------"
          echo "Drive gumiho10q:"
          rclone ls drive-gumiho10q:
          echo "-----------------------------------------------"
          echo "Mega nhatgg81:"
          rclone ls mega-nhatgg81:
          echo "-----------------------------------------------"
          echo "OneDrive dgbaodev:"
          rclone ls onedrive-dgbaodev:
          echo "-----------------------------------------------"